# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.16"
  i386: "ghcr.io/home-assistant/i386-base:3.16"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Open Doñita add-on"
  org.opencontainers.image.description: "Open Doñita server add-on."
  org.opencontainers.image.source: "https://github.com/jmservera/jm-hassio-addons"
  org.opencontainers.image.licenses: "GNU General Public License v3.0"
