name: "Open Doñita"
description: "The Open Doñita server for managing your Cecotec Conga"
version: "0.3.3"
slug: "opendonita"
url: https://github.com/jmservera/opendonita-fork
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
panel_icon: mdi:robot-vacuum
ports:
  8099/tcp: 8099
  20008/tcp: 20008
map:
  - config:rw

