name: "Open Doñita"
description: "The Open Doñita server"
version: "0.1.0"
slug: "open_donita"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: 8000
  20008/tcp: 20008
environment:
  HOME: /config
  RUNNINGINDOCKER: '1'
