name: "Open Doñita"
description: "The Open Doñita server"
version: "0.1.0"
slug: "opendonita"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress-port: 80
ports:
  80/tcp:
  20008/tcp: 20008
map:
  - config:rw
environment:
  HOME: /config
  RUNNINGINDOCKER: '1'
