name: "Open Doñita"
description: "The Open Doñita server"
version: "0.2.1"
slug: "opendonita"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
panel_icon: mdi:robot-vacuum
ports:
  8099/tcp: 8099
  20008/tcp: 20008
map:
  - config:rw

