name: "Open Doñita"
description: "The Open Doñita server"
version: "0.1.0"
slug: "opendonita"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ports:
  8099/tcp: 
  20008/tcp: 20008
host-network: true
map:
  - config:rw

