name: "Open Doñita"
description: "The Open Doñita server for managing your Cecotec Conga"
version: "0.3.6"
slug: "opendonita"
url: https://github.com/jmservera/opendonita-fork
stage: experimental
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 80
panel_icon: mdi:robot-vacuum
ports:
  80/tcp: 80
  20008/tcp: 20008
map:
  - config:rw
image: "ghcr.io/jmservera/{arch}-addon-opendonita"
